language: php

php:
  - 5.6

before_install:
  - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master squizlabs/php_codesniffer=*
  - composer install --dev --ignore-platform-reqs

script:
  - mkdir -p build/logs
  # - php vendor/bin/phpcbf --standard=ruleset.xml src
  # - php vendor/bin/phpcs --standard=ruleset.xml src
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v